### ISSUE TITLE
Event-Driven Service Discovery Documentation Update

### ISSUE THREAD

**Issue by kreynoldsf5** [F5Networks/f5-appsvcs-extension#116]
##### Do you already have an issue opened with F5 support?
No.

##### ISSUE TYPE

 Documentation Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.12.0 
f5-service-discovery-1.1.0 <-- more relevant to this issue
```

##### BIGIP VERSION

```
>13.x
```

###### ISSUE1
For using 'event driven' service discovery the [cloudocs documentation](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html?highlight=event%20driven#event-driven-service-discovery-for-use-in-the-docker-container) specifies an incorrect endpoint for the worker:

```
https://<host>/mgmt/shared/appsvcs-discovery/task/~<tenant name>~<application name>~<pool name>/nodes
```

The correct endpoint should be:

```
https://<host>/mgmt/shared/service-discovery/task/~<tenant name>~<application name>~<pool name>/nodes
```

The documentation error is made in a few places. Earlier versions of the f5-service-discovery worker (<1.1.0) may use the endpoint documented -- in which case the documentation will need to differentiate endpoints based on AS3 version and f5-service-discovery version. The f5-service-discovery package name changed during the AS3 3.10 release (as [documented here](https://github.com/F5Networks/f5-appsvcs-extension/issues/87)). 

###### ISSUE2
Please provide disambiguation around the use of this feature. The documentation section title is "Event-Driven Service Discovery for use in the Docker Container". The feature works whether using [AS3 in a container](https://hub.docker.com/r/f5devcentral/f5-as3-container) or natively on a BIG-IP. The section title is causing confusion as to where event-driven service discovery can be used.

##### STEPS TO REPRODUCE

Create a tenant that uses event-driven service discovery.

```json
{
    "class": "ADC",
    "schemaVersion": "3.12.0",
    "Tenant1": {
        "class": "Tenant",
        "App1": {
            "class": "Application",
            "template": "http",
            "serviceMain": {
            "class": "Service_HTTP",
            "virtualAddresses": [
                "10.0.2.10"
            ],
            "pool": "web_pool1"
            },
            "web_pool1": {
            "class": "Pool",
                "monitors": [
                    "http"
                ],
            "members": [{
                "servicePort": 80,
                "addressDiscovery": "event"
            }]
            }
        }
    }
```

Attempt to use the documented event-driven service discovery endpoint to alter pool members. POST to https://{{BIG-IP}}/mgmt/shared/appsvcs-discovery/task/~Tenant1~App1~web_pool1/nodes

```json
[
    {
        "id": "newNode1",
        "ip": "192.0.2.3"
    },
    {
        "id": "newNode2",
        "ip": "192.0.2.4"
    }
]
```

##### EXPECTED RESULTS

200 and the POST successful
```json
{"code":200,"id":"~Tenant1~App1~web_pool1","updateInterval":0,"provider":"event","providerOptions":{"type":"event","previousNodes":[{"id":"/Tenant1/newNode1","ip":"192.0.2.3"},{"id":"/Tenant1/newNode2","ip":"192.0.2.4"}],"nodeList":[{"id":"/Tenant1/newNode1","ip":"192.0.2.3"},{"id":"/Tenant1/newNode2","ip":"192.0.2.4"}]},"resources":[{"type":"pool","path":"/Tenant1/App1/web_pool1","options":{"servicePort":80,"connectionLimit":0,"rateLimit":"disabled","dynamicRatio":1,"ratio":1,"priorityGroup":0,"monitor":"default"},"requiresNodes":true}],"kind":"shared:service-discovery:taskstate","lastRun":"2019-07-24T17:29:21.970Z","nodePrefix":"/Tenant1/"}
```

##### ACTUAL RESULTS

```json
{
  "code": 404,
  "message": "Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.",
  "referer": "127.0.0.1",
  "restOperationId": 9619385,
  "errorStack": [
    "com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:572)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:44)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:314)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:311)",
    "at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:150)",
    "at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:342)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.onPost(ForwarderPassThroughWorker.java:763)",
    "at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1161)",
    "at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1119)",
    "at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1385)",
    "at com.f5.rest.common.RestServer.access$000(RestServer.java:48)",
    "at com.f5.rest.common.RestServer$1.run(RestServer.java:329)",
    "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",
    "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
    "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
    "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
    "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)",
    "at java.util.concurrent.ThreadPoolExecuto* Connection #0 to host localhost left intactr$Worker.run(ThreadPoolExecutor.java:615)",
    "at java.lang.Thread.run(Thread.java:745)\n"
  ],
  "kind": ":resterrorresponse"
}
```

**Comment by JosephPJordan** [comment]
Hi @kreynoldsf5, thank you for the issue.  The corrections are already staged and will be pushed out with the release of AS3 3.13 on Tuesday.
