### ISSUE TITLE
Unable to POST more than 70 nodes to service discovery endpoint.

### ISSUE THREAD

**Issue by kedargslab** [F5Networks/f5-appsvcs-extension#188]
##### Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

##### ISSUE TYPE

 - Bug Report

##### AS3 BUILD/ VERSION
v3.14.0-4

##### BIGIP VERSION
v13.1 
##### SUMMARY
After configuring service discovery EP, unable to POST more than 70 endpoints to service discovery endpoint in same go.
##### STEPS TO REPRODUCE
- Configured Service discovery for BigIP
- Using POSTMAN we tried to post data in following format with the url below :

Service discovery url : https://10.107.0.22/mgmt/shared/service-discovery/task/~Part_11~Virt_server~web_pool/nodes   

Method : POST

Data : ( per node ) - the scaled up post had 70+ nodes in below format.

[

    {

        "ip": "12.1.1.1",

        "id": "12.1.1.1"

    }

]

Observations : 

75 nodes ( and above): 400 BAD REQUEST: 1m 28s

- It was observed that the BigIP went unreachable for a few minutes and looks like the services restarted.

Error response from bigIP : 

{

    "code": 400,

    "message": "remoteSender:10.107.0.5, method:POST ",

    "originalRequestBody": "[\n    {\n        \"ip\": \"12.1.1.1\",\n        \"id\": \"12.1.1.1\"\n    },\n    {\n        \"ip\": \"12.1.1.2\",\n        \"id\": \"12.1.1.2\"\n    },\n    {\n        \"ip\": \"12.1.1.3\",\n        \"id\": \"12.1.1.3\"\n    },\n    {\n        \"ip\": \"12.1.1.4\",\n        \"id\": \"12.1.1.4\"\n    },\n    {\n        \"ip\": \"12.1.1.5\",\n        \"id\": \"12.1.1.5\"\n    },\n    {\n        \"ip\": \"12.1.1.6\",\n        \"id\": \"12.1.1.6\"\n    },\n    {\n        \"ip\": \"12.1.1.7\",\n        \"id\": \"12.1.1.7\"\n    },\n    {\n        \"ip\": \"12.1.1.8\",\n        \"id\": \"12.1.1.8\"\n    },\n    {\n        \"ip\": \"12.1.1.9\",\n        \"id\": \"12.1.1.9\"\n    },\n    {\n        \"ip\": \"12.1.1.10\",\n        \"id\": \"12.1.1.10\"\n    },\n    {\n        \"ip\": \"12.1.1.11\",\n        \"id\": \"12.1.1.11\"\n    },\n    {\n        \"ip\": \"12.1.1.12\",\n        \"id\": \"12.1.1.12\"\n    },\n    {\n        \"ip\": \"12.1.1.13\",\n        \"id\": \"12.1.1.13\"\n    },\n    {\n        \"ip\": \"12.1.1.14\",\n        \"id\": \"12.1.1.14\"\n    },\n    {\n        \"ip\": \"12.1.1.15\",\n        \"id\": \"12.1.1.15\"\n    },\n    {\n        \"ip\": \"12.1.1.16\",\n        \"id\": \"12.1.1.16\"\n    },\n    {\n        \"ip\": \"12.1.1.17\",\n        \"id\": \"12.1.1.17\"\n    },\n    {\n        \"ip\": \"12.1.1.18\",\n        \"id\": \"12.1.1.18\"\n    },\n    {\n        \"ip\": \"12.1.1.19\",\n        \"id\": \"12.1.1.19\"\n    },\n    {\n        \"ip\": \"12.1.1.20\",\n        \"id\": \"12.1.1.20\"\n    },\n    {\n        \"ip\": \"12.1.1.21\",\n        \"id\": \"12.1.1.21\"\n    },\n    {\n        \"ip\": \"12.1.1.22\",\n        \"id\": \"12.1.1.22\"\n    },\n    {\n        \"ip\": \"12.1.1.23\",\n        \"id\": \"12.1.1.23\"\n    },\n    {\n        \"ip\": \"12.1.1.24\",\n        \"id\": \"12.1.1.24\"\n    },\n    {\n        \"ip\": \"12.1.1.25\",\n        \"id\": \"12.1.1.25\"\n    },\n    {\n        \"ip\": \"12.1.1.26\",\n        \"id\": \"12.1.1.26\"\n    },\n    {\n        \"ip\": \"12.1.1.27\",\n        \"id\": \"12.1.1.27\"\n    },\n    {\n        \"ip\": \"12.1.1.28\",\n        \"id\": \"12.1.1.28\"\n    },\n    {\n        \"ip\": \"12.1.1.29\",\n        \"id\": \"12.1.1.29\"\n    },\n    {\n        \"ip\": \"12.1.1.30\",\n        \"id\": \"12.1.1.30\"\n    },\n    {\n        \"ip\": \"12.1.1.31\",\n        \"id\": \"12.1.1.31\"\n    },\n    {\n        \"ip\"",

    "referer": "10.107.0.5",

    "restOperationId": 1470018,

    "errorStack": [

        "java.util.concurrent.TimeoutException: remoteSender:10.107.0.5, method:POST ",

        "at com.f5.rest.common.RestWorker.logAndFailExpiredOperation(RestWorker.java:3099)",

        "at com.f5.rest.common.RestWorker.checkForExpiredOperations(RestWorker.java:3088)",

        "at com.f5.rest.common.RestServer.checkAndExpirePendingWorkerOperations(RestServer.java:1457)",

        "at com.f5.rest.common.RestServer.access$400(RestServer.java:48)",

        "at com.f5.rest.common.RestServer$4.run(RestServer.java:1430)",

        "at com.f5.rest.common.ScheduleTaskManager$2$1.run(ScheduleTaskManager.java:123)",

        "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",

        "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",

        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",

        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",

        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)",

        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)",

        "at java.lang.Thread.run(Thread.java:748)",

        "Suppressed: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $",

        "\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)",

        "\tat com.google.gson.Gson.fromJson(Unknown Source)",

        "\tat com.google.gson.Gson.fromJson(Unknown Source)",

        "\tat com.google.gson.Gson.fromJson(Unknown Source)",

        "\tat com.f5.rest.common.RestOperation.getBody(RestOperation.java:1586)",

        "\tat com.f5.rest.common.RestOperation.setErrorResponseBody(RestOperation.java:2544)",

        "\tat com.f5.rest.common.RestOperation.fail(RestOperation.java:2485)",

        "\tat com.f5.rest.common.RestWorker.logAndFailDrainedOperation(RestWorker.java:1318)",

        "\t... 13 more",

        "Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $",

        "\tat com.google.gson.stream.JsonReader.beginObject(Unknown Source)",

        "\t... 21 more\n"

    ],

    "kind": ":resterrorresponse"

}

 

Logs observed in restnoded.log :

Tue, 10 Sep 2019 09:29:06 GMT - finest: [LoaderWorker] '/var/config/rest/iapps/f5-service-discovery/nodejs/lib/util.js' is not a worker, skipping

Tue, 10 Sep 2019 09:29:07 GMT - config: [RestWorker] /shared/service-discovery/task has started. Name:RestWorkerTask

Tue, 10 Sep 2019 09:29:07 GMT - info: [f5-service-discovery: Task.js] Task ~Part_9~iqeo~ZX4o4oGCS2BOuss4iSIndzIPQAb7h1T2dkLfvjg3D failed: The var "nodes" must be instantiated and be an array for comparison

Tue, 10 Sep 2019 09:29:14 GMT - warning: [appsvcs] {"message":"Unable to register device for telemetry: Error: getaddrinfo EAI_AGAIN product.apis.f5.com:443\n    at Object.exports._errnoException (util.js:907:11)\n    at errnoException (dns.js:32:15)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)","level":"warning"}

Tue, 10 Sep 2019 09:29:14 GMT - severe: [appsvcs] {"message":"Error: Command failed: ls /var/config/rest/iapps/f5-appsvcs/encryptedDeclaration\nls: cannot access /var/config/rest/iapps/f5-appsvcs/encryptedDeclaration: No such file or directory\n","code":"2","level":"error"}

Tue, 10 Sep 2019 09:29:14 GMT - config: [RestWorker] /shared/appsvcs has started. Name:RestWorker

Tue, 10 Sep 2019 09:29:14 GMT - info: [f5-service-discovery: Task.js] Task ~Part_10~7f4tRBFgFs7bLLQqR45Br6wnXUXUb4rBBsXB9WHKsLI3D failed: The var "nodes" must be instantiated and be an array for comparison

Tue, 10 Sep 2019 09:29:17 GMT - info: [f5-service-discovery: Task.js] Task ~Part_10~N8uhvRBWFLRIQOyHRzzyeon~7dLuRDFqy2BdP8~kqMEc3D failed: The var "nodes" must be instantiated and be an array for comparison

Tue, 10 Sep 2019 09:29:20 GMT - info: [f5-service-discovery: Task.js] Task ~Part_10~tujdLZIvPRE8fMVto4xP9THbgO2BkFWshKS8CDZPRPD43D failed: The var "nodes" must be instantiated and be an array for comparison

Tue, 10 Sep 2019 09:29:24 GMT - info: [f5-service-discovery: Task.js] Task ~Part_11~WXU5SyPaTDUeHplEOULUYgitgNEa9LEZ6Lo2~74amQg3D failed: The var "nodes" must be instantiated and be an array for comparison

**Comment by dstokesf5** [comment]
Thank you for reporting this issue. I have added it to our internal product backlog as AUTOTOOL-969.

**Comment by kedargslab** [comment]
Found during testing integration with F5 ACI ServiceCenter

**Comment by chen23** [comment]
I believe this issue should be fixed in AS3 3.24.

**Comment by dstokesf5** [comment]
@kedargslab Does the latest release resolve this issue for you?

**Comment by dstokesf5** [comment]
Closing for inactivity. If you are still encountering issue, please reopen this ticket for a file a new one.
