### ISSUE TITLE
Nodes are sometimes not assigned to pool while using AWS service discovery

### ISSUE THREAD

**Issue by michal-malec** [F5Networks/f5-appsvcs-extension#215]
### Environment
 * Application Services Version: 3.16.0
 * BIG-IP Version: 15.0.1 (Build: 0.0.11)

### Summary
While using pool member service discovery in AWS I observed that sometimes AS3 tries to add nodes to pool before the pool is created. In a result there are no nodes in pool.

### Steps To Reproduce
1. Here is a part of AS3 template which creates pool:
```json
 "cluster_pool": {
          "class": "Pool",
          "monitors": [
            {
              "use": "cluster_http_monitor"
            }
          ],
          "members": [
            {
              "servicePort": 80,
              "addressDiscovery": "aws",
              "updateInterval": 10,
              "tagKey": "Name",
              "tagValue": "instance-default",
              "addressRealm": "private",
              "region": "eu-central-1"
            }
          ]
        },
```

2. Here is an extract from logs (/var/log/restnoded/restnoded.log)
```
Fri, 17 Jan 2020 19:26:16 GMT - finest: socket 198 opened
Fri, 17 Jan 2020 19:26:18 GMT - fine: [f5-service-discovery: restWorkerTask.js] Got service discovery task request
Fri, 17 Jan 2020 19:26:22 GMT - info: [f5-service-discovery: Task.js] Task ~ Server~H~kUy9RaU47Ra5VueYgqx0E4XXTqG16iZwIVItFu1683D failed: Command failed: tmsh -a create ltm node /Server/aws-i-0524b1c4ed181b904-private address 172.20.1.41 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/Server/aws-i-0524b1c4ed181b904-private) folder does not exist

Fri, 17 Jan 2020 19:26:22 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a create ltm node /Server/aws-i-0524b1c4ed181b904-private address 172.20.1.41 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/Server/aws-i-0524b1c4ed181b904-private) folder does not exist

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Fri, 17 Jan 2020 19:26:22 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Fri, 17 Jan 2020 19:26:28 GMT - finest: socket 198 closed
Fri, 17 Jan 2020 19:26:28 GMT - finest: socket 199 opened
Fri, 17 Jan 2020 19:26:33 GMT - finest: socket 199 closed
Fri, 17 Jan 2020 19:26:33 GMT - finest: socket 200 opened
Fri, 17 Jan 2020 19:26:36 GMT - info: [f5-service-discovery: Task.js] Task ~ Server~H~kUy9RaU47Ra5VueYgqx0E4XXTqG16iZwIVItFu1683D failed: Command failed: tmsh -a modify ltm pool /Server/Application/cluster_pool members replace-all-with { aws-i-0524b1c4ed181b904-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-08004c6bd21a100ad-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-0c1c212c0501b10a9-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/Server/Application/cluster_pool) was not found.

Fri, 17 Jan 2020 19:26:36 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a modify ltm pool /Server/Application/cluster_pool members replace-all-with { aws-i-0524b1c4ed181b904-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-08004c6bd21a100ad-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-0c1c212c0501b10a9-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/Server/Application/cluster_pool) was not found.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Fri, 17 Jan 2020 19:26:39 GMT - finest: socket 200 closed
Fri, 17 Jan 2020 19:26:39 GMT - finest: socket 201 opened
Fri, 17 Jan 2020 19:26:44 GMT - finest: socket 201 closed
Fri, 17 Jan 2020 19:26:44 GMT - finest: socket 202 opened
Fri, 17 Jan 2020 19:26:50 GMT - finest: socket 202 closed
```
The most important statement is `The requested pool (/Server/Application/cluster_pool) was not found.`
It doesn't happen always.

### Expected Behavior
I expect that nodes are added to pool.

### Actual Behavior
There are no nodes in pool.

**Comment by JeffGiroux** [comment]
I'm running into this same issue in my Azure deployments. I'm doing AS3 with service discovery. The VS is created, the pool is created, the node is auto discovered. But...the node fails to be associated with pool. I see a few errors in the logs.

AS3 3.20.0
TS 1.12.0
DO 1.13.0
BIG-IP 15.1.0.2
Azure Standard DS4

You can repro by referencing my repo here:
https://github.com/JeffGiroux/f5_terraform/tree/master/Azure/Secure_Enclave_Public_DMZ

Error Logs
```
Tue, 02 Jun 2020 23:44:06 GMT - info: [f5-service-discovery: Task.js] Task ~Sample_01~dHQQSfqHWQsFyUOn5Y6ArzOWoPaDpfzJir4AZezssz83D failed: Command failed: tmsh -a create ltm node /Sample_01/azure-giroux1_rg-giroux1-backend01-ext-nic-private address 10.80.1.101 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/Sample_01/azure-giroux1_rg-giroux1-backend01-ext-nic-private) folder does not exist


Tue, 02 Jun 2020 23:44:06 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a create ltm node /Sample_01/azure-giroux1_rg-giroux1-backend01-ext-nic-private address 10.80.1.101 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/Sample_01/azure-giroux1_rg-giroux1-backend01-ext-nic-private) folder does not exist

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Tue, 02 Jun 2020 23:44:06 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Tue, 02 Jun 2020 23:44:11 GMT - finest: socket 237 closed
```

And more...
```
Tue, 02 Jun 2020 23:44:14 GMT - info: [f5-service-discovery: Task.js] Task ~Sample_01~dHQQSfqHWQsFyUOn5Y6ArzOWoPaDpfzJir4AZezssz83D failed: Command failed: tmsh -a modify ltm pool /Sample_01/A1/web_pool members replace-all-with { azure-giroux1_rg-giroux1-backend01-ext-nic-private:80 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/Sample_01/A1/web_pool) was not found.

Tue, 02 Jun 2020 23:44:14 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a modify ltm pool /Sample_01/A1/web_pool members replace-all-with { azure-giroux1_rg-giroux1-backend01-ext-nic-private:80 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/Sample_01/A1/web_pool) was not found.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

## Workaround
As stated above, all items seem to be created successfully by AS3. But...the node discovered by AS3 SD does not get associated to pool. As a result, VIP is down. Workaround is to simply restart restnoded, and the pool will populate with already discovered nodes. Alternatively, you can manually add the node to the pool...but that doesn't fix the restnoded issue.
```
restart sys service restnoded
```

**Comment by nergalex** [comment]
same symptom and workaround with this configuration:
- AS3 : 3.18.0-4
- DO : 1.11.1-1
- TS : 1.10.0-2

And also wrong server information seen in BIG-IQ 7.0 and 7.1: always 1 pool member

**Comment by dstokesf5** [comment]
Thanks to @JeffGiroux 's work, I was able to reproduce this failure by adding WAF policy onto a basic service discovery declaration. I have added this to our internal product backlog as AUTOTOOL-1636.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
