### ISSUE TITLE
TEST_AS3_Basics lock always blocks self-test

### ISSUE THREAD

**Issue by ColinHeathman** [F5Networks/f5-appsvcs-extension#23]
##### ISSUE TYPE
 - Bug Report

##### AS3 BUILD/ VERSION

```
f5-appsvcs-3.2.0-7
```

##### BIGIP VERSION

```
BIG-IP 12.1.2 Build 2.0.276 Hotfix HF2
```

##### SUMMARY

Error on self test:
```
Device localhost configuration operation in progress for (TEST_AS3_Basics), please try again in 5 minutes
```

##### STEPS TO REPRODUCE

Restart restnoded
`tmsh restart /sys service restnoded`

POST to `https://{{host}}/mgmt/shared/appsvcs/selftest` using a service account (not `admin`)

##### EXPECTED RESULTS

Self test suite passes

##### ACTUAL RESULTS

```
{
    "code": 500,
    "message": "POST http://admin:XXXXXX@localhost:8100/mgmt/shared/appsvcs/declare submit tests response=503 body={\"status\":503,\"retryAfter\":300,\"message\":\"Device localhost configuration operation in progress for (TEST_AS3_Basics), please try again in 5 minutes\",\"code\":503,\"declarationFullId\":\"\"}",
    "originalRequestBody": "",
    "referer": "restnoded",
    "restOperationId": 0,
    "kind": ":resterrorresponse"
}
```
Gist of /var/log/restnoded/restnoded.log, including startup

[https://gist.github.com/ColinHeathman/a82774e450bc037b6d51087993b9c35c](https://gist.github.com/ColinHeathman/a82774e450bc037b6d51087993b9c35c)

**Comment by kaustriaf5** [comment]
Did initial investigation with @ColinHeathman on this one, and manually clearing out the lock icall objects could not be done, as they seem to not exist.

**Comment by ColinHeathman** [comment]
A different error occurs after upgrading to AS 3.3.0 ( still on BIG-IP 12.1.2 Build 2.0.276 Hotfix HF2 )

self test still fails, but there is a different error message

```
{
    "code": 500,
    "message": "Cannot convert undefined or null to object",
    "originalRequestBody": "",
    "referer": "restnoded",
    "restOperationId": 0,
    "kind": ":resterrorresponse"
}
```

Error message in restnoded.log (formatted for clarity):
```
severe: [ErrorHandlingModule] RestOperation failed: "/shared/appsvcs/selftest". 
{
    "code": 500,
    "message": "POST http://admin:XXXXXX@localhost:8100/mgmt/shared/appsvcs/declare submit tests response=500 body={\"code\":500,\"message\":\"Cannot convert undefined or null to object\",\"originalRequestBody\":\"\",\"referer\":\"restnoded\",\"restOperationId\":0,\"kind\":\":resterrorresponse\"}",
    "referer": "restnoded",
    "originalRequestBody": "{}",
    "errorStack": [
        "Error: POST http://admin:XXXXXX@localhost:8100/mgmt/shared/appsvcs/declare submit tests response=500 body={\"code\":500,\"message\":\"Cannot convert undefined or null to object\",\"originalRequestBody\":\"\",\"referer\":\"restnoded\",\"restOperationId\":0,\"kind\":\":resterrorresponse\"}",
        "at IncomingMessage.<anonymous> (/var/config/rest/iapps/f5-appsvcs/nodejs/util.js:450:25)",
        "at emitNone (events.js:72:20)",
        "at IncomingMessage.emit (events.js:166:7)",
        "at endReadableNT (_stream_readable.js:921:12)",
        "at nextTickCallbackWith2Args (node.js:442:9)",
        "at process._tickCallback (node.js:356:17)"
    ]
}
```


Full restnoded.log: https://gist.github.com/ColinHeathman/6e61ab24d496239115c5b99908f5700c

**Comment by kaustriaf5** [comment]
@ColinHeathman are you experiencing the same issues with 3.5 release?

**Comment by malbertus** [comment]
I'm having a similar issue, though now it's `urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb` causing the 500 response. Coincidentally, this is the ID given to the Declaration Using All Properties [appendix](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3/refguide/all-properties.html?highlight=uuid%205cff22e8%20d3d1%20b0b193f812eb) so I assume that the intent is to create and delete this declaration after posting to the selftest api. 

Problem seems to be how long it takes to create and delete this selftest declaration as the 500 response is given 60 seconds after initial POST, yet the declaration appears to be created and deleted successfully, suggesting the selftest passes.

```
Mon, 22 Oct 2018 06:09:54 GMT - fine: [appsvcs] {"message":"got transaction lock; fetch previous decl","level":"debug"}
Mon, 22 Oct 2018 06:09:58 GMT - info: [appsvcs] {"action":"deploy","tenant":"Common","applications":["Shared"],"level":"info"}
Mon, 22 Oct 2018 06:09:58 GMT - info: [appsvcs] {"action":"deploy","tenant":"AS3_Basics_01","applications":["Shared","A1_01","A2_01","A3_01","A4_01","A5_01","A6_01","A7_01","A8_01","A9_01","A10_01","A11_01","A12_01","A13_01","A14_01","A15_01","A16_01","A17_01","A18_01","A19_01","A20_01","A21_01","A22_01"],"level":"info"}
Mon, 22 Oct 2018 06:09:58 GMT - info: [appsvcs] {"action":"deploy","tenant":"AS3_Basics_02","applications":["Shared","A1_02","A2_02","A3_02","A4_02","A5_02","A6_02","A7_02","A8_02","A9_02","A10_02","A11_02","A12_02","A13_02","A14_02","A15_02","A16_02","A17_02","A18_02","A19_02","A20_02","A21_02","A22_02","A23_02","A24_02","A26_02"],"level":"info"}
Mon, 22 Oct 2018 06:09:58 GMT - info: [appsvcs] {"action":"deploy","tenant":"AS3_Basics_03","applications":["Shared","A1_03","A2_03","A3_03","A4_03","A5_03","A6_03","A7_03","A8_03","A9_03"],"level":"info"}
<SNIP>
Mon, 22 Oct 2018 06:10:55 GMT - info: [appsvcs] {"message":"Error: Device localhost configuration operation in progress for (urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb), please try again in 2 minutes","stack":["Error: Device localhost configuration operation in progress for (urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb), please try again in 2 minutes","/var/config/rest/iapps/f5-appsvcs/nodejs/declarationRequestHandler.js:1389:37","process._tickCallback (node.js:438:9)"],"level":"info"}
Mon, 22 Oct 2018 06:10:55 GMT - severe: [appsvcs] {"message":"POST http://admin:XXXXXX@localhost:8100/mgmt/shared/appsvcs/declare submit tests response=503 body={\"code\":503,\"declarationFullId\":\"\",\"message\":\"Device localhost configuration operation in progress for (urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb), please try again in 2 minutes\"}","level":"error"}
Mon, 22 Oct 2018 06:10:55 GMT - severe: [ErrorHandlingModule] RestOperation failed: "/shared/appsvcs/selftest". {"error":{"code":500,"message":"POST http://admin:XXXXXX@localhost:8100/mgmt/shared/appsvcs/declare submit tests response=503 body={\"code\":503,\"declarationFullId\":\"\",\"message\":\"Device localhost configuration operation in progress for (urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb), please try again in 2 minutes\"}","innererror":{"referer":"restnoded","originalRequestBody":"\"{}\"","errorStack":[]}}}
<SNIP>
Mon, 22 Oct 2018 06:10:59 GMT - fine: [appsvcs] {"message":"deployed= 5 good 0 bad 5 changes","level":"debug"}
Mon, 22 Oct 2018 06:10:59 GMT - fine: [appsvcs] {"message":"5 changes, save current declaration for later","level":"debug"}
Mon, 22 Oct 2018 06:10:59 GMT - fine: [appsvcs] {"message":"purge stored decls in excess of 0","level":"debug"}
Mon, 22 Oct 2018 06:10:59 GMT - fine: [appsvcs] {"message":"unlocking transaction","level":"debug"}
<FINISH>
```

**Comment by ColinHeathman** [comment]
@kaustriaf5 We're now getting the same error messages as malbertus after upgrading to BIGIP version 13.1 and AS3 version 3.5.

We have the same `urn:uuid:5cff22e8-d3d1-6056-8577-b0b193f812eb` instead of `TEST_AS3_Basics`


Previously we couldn't deploy any tenants at all. I've had success POSTing and DELETEing some simple tenants after upgrading.

**Comment by kaustriaf5** [comment]
@ColinHeathman @malbertus thanks for reporting.
I opened a new bug #33 to track the current issue and closing this one.
