### ISSUE TITLE
Version 12.1.5 Public URI path not registered with AS3 3.18 and 3.19

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-appsvcs-extension#264]
### Environment
 * Application Services Version: 3.18.0
 * BIG-IP Version: 12.1.5 AWS, used this AMI ID ami-0f6a9261c48d07860 in us-east-1

### Summary
Deployed BIG-IP v12.1.5 in AWS. Version AS3 3.18 and 3.19 cause 400 error "Public URI path not registered". This does not happen on 3.17 or lower. With version 3.17 and older, I can GET /info successfully and /declare. AS3 v3.18+ does not seem to install and/or work on BIG-IP v12.x.

### Steps To Reproduce
1. Deploy 12.1.5 BIG-IP in AWS
2. Install AS3 3.18. GET on /info
3. Observe the following error response:
```
{
    "code": 404,
    "message": "Public URI path not registered",
    "referer": "68.3.105.168",
    "restOperationId": 56329,
    "errorStack": [
        "com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered",
        "at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:355)",
        "at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:37)",
        "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:216)",
        "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:213)",
        "at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:148)",
        "at com.f5.rest.workers.EvaluatePermissions.access$000(EvaluatePermissions.java:22)",
        "at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:88)",
        "at com.f5.rest.workers.EvaluatePermissions$1.completed(EvaluatePermissions.java:84)",
        "at com.f5.rest.common.RestOperation.complete(RestOperation.java:2273)",
        "at com.f5.rest.workers.AuthTokenWorker.onGet(AuthTokenWorker.java:209)",
        "at com.f5.rest.common.RestCollectionWorker.callDerivedRestMethod(RestCollectionWorker.java:801)",
        "at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1034)",
        "at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1355)",
        "at com.f5.rest.common.RestServer.access$000(RestServer.java:45)",
        "at com.f5.rest.common.RestServer$1.run(RestServer.java:316)",
        "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",
        "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
        "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
        "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)",
        "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)",
        "at java.lang.Thread.run(Thread.java:748)\n"
    ],
    "kind": ":resterrorresponse"
}
```

### Expected Behavior
AS3 should successfully install and allow me to GET endpoint URLs. 

Here is what v3.17 looks like. It actually works on 12.1.5.

```
{
    "version": "3.17.1",
    "release": "1",
    "schemaCurrent": "3.17.0",
    "schemaMinimum": "3.0.0"
}
```

### Actual Behavior
AS3 doesn't function or install with 3.18+ and BIG-IP 12.1.5. It works successfully with other versions of AS3 and BIG-IP v12.1.5

**Comment by JeffGiroux** [comment]
This was caused by the initial RPM install failing. It failed because the RPM was located in /config/cloud instead of /var/config/rest/downloads. Apparently v12 BIG-IP needs the AS3 RPM in /var/config/rest/downloads...otherwise it fails. And it causes future installs of that same AS3 package to fail endpoint calls.

This is directly related to CFT templates which use /config/cloud for the RPM download and install source.

https://github.com/F5Networks/f5-aws-cloudformation/issues/103

#Workaround
See comments in https://github.com/F5Networks/f5-aws-cloudformation/issues/103. Make sure you install AS3 on a v12 from /var/config/rest/downloads.

3.18+ does indeed work on v.12. Closing
