### ISSUE TITLE
AS3 occasionally fails after BIG-IP update to 15.1.0.4

### ISSUE THREAD

**Issue by michal-malec** [F5Networks/f5-appsvcs-extension#300]
### Environment
 * Application Services Version: 3.19.1
 * BIG-IP Version: BIG-IP 15.1.0.4 Build 0.0.6 Point Release 4

### Summary
I am sending AS3 declaration in async mode. In about 60% of cases it fails after about 3 minutes. This issue did not exist in BIG-IP 15.0.1.1 Build 0.0.3.

Issue may be connected with https://github.com/F5Networks/f5-appsvcs-extension/issues/215, however now AS3 creates only partition not everything except of pool.

### Steps To Reproduce
1. Submit declaration in async mode.
2. Check task status regularly.
3. After about 3 minutes you will receive an error:
```
{"code":422,"message":"declaration failed","response":"GET http://admin:XXXXXX@localhost:8100/mgmt/tm/task/cli/script/1594395937346312 checking cli script status response=404 body={\"code\":404,\"message\":\"Task not found - ID: 1594395937346312 user: admin\",\"errorStack\":[],\"apiError\":1}","host":"localhost","tenant":"ABCD","runTime":93826,"level":"debug"}
```

### Last part of logs from `restnod.log`
```
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"audit ABCD","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"Begin parsing desired ABCD config","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - config: [appsvcs] {"message":"parsing desired ABCD config time: 0.096 seconds","level":"notice"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"Begin parsing current ABCD config","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"tenant ABCD lacks a partition","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - config: [appsvcs] {"message":"parsing current ABCD config time: 0.02 seconds","level":"notice"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"Begin generating ABCD diff","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - config: [appsvcs] {"message":"generating ABCD diff time: 0.021 seconds","level":"notice"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [appsvcs] {"message":"Begin updating ABCD","level":"debug"}
Fri, 10 Jul 2020 15:45:31 GMT - fine: [f5-service-discovery: restWorkerTask.js] Got service discovery task request
Fri, 10 Jul 2020 15:45:35 GMT - info: [f5-service-discovery: Task.js] Task ~ABCD~Kz0eIu5qGYcr8pEJT4f1k2x9gJhGqc5SpSEmHhow1TQ3D failed: Command failed: tmsh -a create ltm node /ABCD/aws-i-01c4e766befeee594-private address 172.20.1.42 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/ABCD/aws-i-01c4e766befeee594-private) folder does not exist

Fri, 10 Jul 2020 15:45:35 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a create ltm node /ABCD/aws-i-01c4e766befeee594-private address 172.20.1.42 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/ABCD/aws-i-01c4e766befeee594-private) folder does not exist

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Fri, 10 Jul 2020 15:45:35 GMT - fine: [f5-service-discovery: restWorkerTask.js] service discovery task succeeded
Fri, 10 Jul 2020 15:45:35 GMT - fine: [appsvcs] {"message":"generating tmsh commands and pre-script iControlRest calls","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"getting whitelist","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"setting whitelist","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"executing pre-script iControl calls","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"Executing pre-script time: 0 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"uploading cli script","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"Uploading time: 13 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:45:36 GMT - fine: [appsvcs] {"message":"merging cli script","level":"debug"}
Fri, 10 Jul 2020 15:45:37 GMT - fine: [appsvcs] {"message":"Merging time: 967 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:45:37 GMT - fine: [appsvcs] {"message":"running cli script","level":"debug"}
Fri, 10 Jul 2020 15:45:38 GMT - info: [f5-service-discovery: Task.js] Task ~ABCD~Kz0eIu5qGYcr8pEJT4f1k2x9gJhGqc5SpSEmHhow1TQ3D failed: Command failed: tmsh -a create ltm node /ABCD/aws-i-0186344b5e2b2ee5c-private address 172.20.1.96 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/ABCD/aws-i-0186344b5e2b2ee5c-private) folder does not exist

Fri, 10 Jul 2020 15:45:38 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a create ltm node /ABCD/aws-i-0186344b5e2b2ee5c-private address 172.20.1.96 metadata replace-all-with { appsvcs-discovery { } }
01070734:3: Configuration error: Can't associate Node (/ABCD/aws-i-0186344b5e2b2ee5c-private) folder does not exist

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
Fri, 10 Jul 2020 15:45:42 GMT - finest: socket 16 closed
Fri, 10 Jul 2020 15:45:43 GMT - finest: socket 17 opened
Fri, 10 Jul 2020 15:45:44 GMT - info: [f5-service-discovery: Task.js] Task ~ABCD~Kz0eIu5qGYcr8pEJT4f1k2x9gJhGqc5SpSEmHhow1TQ3D failed: Command failed: tmsh -a modify ltm pool /ABCD/Application/abcd_pool members replace-all-with { aws-i-01c4e766befeee594-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-0186344b5e2b2ee5c-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-03dae4cea8d4ecb33-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/ABCD/Application/abcd_pool) was not found.

Fri, 10 Jul 2020 15:45:44 GMT - fine: [f5-service-discovery: Task.js] Error: Command failed: tmsh -a modify ltm pool /ABCD/Application/abcd_pool members replace-all-with { aws-i-01c4e766befeee594-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-0186344b5e2b2ee5c-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } aws-i-03dae4cea8d4ecb33-private:1080 { connection-limit 0 rate-limit disabled dynamic-ratio 1 ratio 1 priority-group 0 monitor default } }
01020036:3: The requested pool (/ABCD/Application/abcd_pool) was not found.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
Fri, 10 Jul 2020 15:45:48 GMT - finest: socket 17 closed
Fri, 10 Jul 2020 15:45:48 GMT - finest: socket 18 opened
Fri, 10 Jul 2020 15:45:54 GMT - finest: socket 18 closed
Fri, 10 Jul 2020 15:45:54 GMT - finest: socket 19 opened
Fri, 10 Jul 2020 15:45:59 GMT - finest: socket 19 closed
Fri, 10 Jul 2020 15:45:59 GMT - finest: socket 20 opened
Fri, 10 Jul 2020 15:46:04 GMT - finest: socket 20 closed
Fri, 10 Jul 2020 15:46:05 GMT - finest: socket 21 opened
Fri, 10 Jul 2020 15:46:10 GMT - finest: socket 21 closed
Fri, 10 Jul 2020 15:46:10 GMT - finest: socket 22 opened
Fri, 10 Jul 2020 15:46:16 GMT - finest: socket 22 closed
Fri, 10 Jul 2020 15:46:16 GMT - finest: socket 23 opened
Fri, 10 Jul 2020 15:46:21 GMT - finest: socket 23 closed
Fri, 10 Jul 2020 15:46:22 GMT - finest: socket 24 opened
Fri, 10 Jul 2020 15:46:27 GMT - finest: socket 24 closed
Fri, 10 Jul 2020 15:46:27 GMT - finest: socket 25 opened
Fri, 10 Jul 2020 15:46:33 GMT - finest: socket 25 closed
Fri, 10 Jul 2020 15:46:33 GMT - finest: socket 26 opened
Fri, 10 Jul 2020 15:46:38 GMT - finest: socket 26 closed
Fri, 10 Jul 2020 15:46:38 GMT - finest: socket 27 opened
Fri, 10 Jul 2020 15:46:44 GMT - finest: socket 27 closed
Fri, 10 Jul 2020 15:46:44 GMT - finest: socket 28 opened
Fri, 10 Jul 2020 15:46:49 GMT - finest: socket 28 closed
Fri, 10 Jul 2020 15:46:50 GMT - finest: socket 29 opened
Fri, 10 Jul 2020 15:46:55 GMT - finest: socket 29 closed
Fri, 10 Jul 2020 15:46:55 GMT - finest: socket 30 opened
Fri, 10 Jul 2020 15:46:56 GMT - fine: [appsvcs] {"message":"Refreshing global mutex lock","level":"debug"}
Fri, 10 Jul 2020 15:47:00 GMT - finest: socket 30 closed
Fri, 10 Jul 2020 15:47:01 GMT - finest: socket 31 opened
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"Running time: 88044 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"verifying cli script","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"Verify time: 19 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"overwriting finished cli script","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"Overwriting time: 9 milliseconds","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - severe: [appsvcs] {"message":"Declaration failed: GET http://admin:XXXXXX@localhost:8100/mgmt/tm/task/cli/script/1594395937346312 checking cli script status response=404 body={\"code\":404,\"message\":\"Task not found - ID: 1594395937346312 user: admin\",\"errorStack\":[],\"apiError\":1}","level":"error"}
Fri, 10 Jul 2020 15:47:05 GMT - config: [appsvcs] {"message":"updating ABCD time: 93.666 seconds","level":"notice"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"code":422,"message":"declaration failed","response":"GET http://admin:XXXXXX@localhost:8100/mgmt/tm/task/cli/script/1594395937346312 checking cli script status response=404 body={\"code\":404,\"message\":\"Task not found - ID: 1594395937346312 user: admin\",\"errorStack\":[],\"apiError\":1}","host":"localhost","tenant":"ABCD","runTime":93826,"level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"deployed= 0 good 1 bad 0 changes","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"0 changes, save current declaration for later","level":"debug"}
Fri, 10 Jul 2020 15:47:05 GMT - fine: [appsvcs] {"message":"store decl on target, blocks=1","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"next purge stored decls in excess of 4","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"stopping refresh of mutex","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"Queuing release of global lock","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"All tenant locks released","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"BIG-IP config saved","level":"debug"}
Fri, 10 Jul 2020 15:47:06 GMT - fine: [appsvcs] {"message":"Finishing async request, setting data-group async task f832135c-5891-474f-90f8-7b46c7fb3032 to indicate the request is completed.","level":"debug"}
```
### Expected Behavior
Declaration is successfully executed in 100% of cases.

### Actual Behavior
Declaration is successfully executed only in about 40% of cases.

**Comment by dstokesf5** [comment]
@michal-malec I was able to run our integration test suite, which sends hundreds of asynchronous requests, on 15.1.0.4 and encountered no issues. Can you provide some additional information about how to reproduce this failure? In particular, a simplified declaration that reproduces this bug would be very helpful.

**Comment by dstokesf5** [comment]
Closing for inactivity. If you are still encountering issue, please reopen this ticket for a file a new one.
