### ISSUE TITLE
Consul Service Discovery: Stuck Task in restnoded.log

### ISSUE THREAD

**Issue by chrisjohnson** [F5Networks/f5-appsvcs-extension#323]
### Environment
 * Application Services Version: f5-appsvcs-3.21.0-4.noarch / f5-service-discovery-1.2.9-2.noarch	
 * BIG-IP Version: 13.1.3.4

### Summary
We've been experimenting with populating the Pools with Consul service discovery. I've been having some difficulties applying large AS3 declarations with hundreds of pools (a separate issue to look into) but one side effect of applying and rolling back declarations over and over is that there appear to be some tasks stuck in the service-discovery plugin

### Steps To Reproduce
I'm not exactly sure

2. Observe the following error response:
`/var/log/restnoded/restnoded.log` has
```
Sat, 15 Aug 2020 05:40:50 GMT - severe: [f5-service-discovery: getNodes.js] error code: ECONNREFUSED message: connect ECONNREFUSED 10.1.28.90:8500
Sat, 15 Aug 2020 05:40:50 GMT - info: [f5-service-discovery: Task.js] Task ~Consul_SD~o4E2BbRTRephiAFnHiBVmx1V9XEvWj6SnPPafJR70~U3D failed: connect ECONNREFUSED 10.1.28.90:8500
Sat, 15 Aug 2020 05:40:50 GMT - fine: [f5-service-discovery: Task.js] Error: connect ECONNREFUSED 10.1.28.90:8500
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
Sat, 15 Aug 2020 05:40:53 GMT - severe: [f5-service-discovery: getNodes.js] error code: ECONNREFUSED message: connect ECONNREFUSED 10.1.28.90:8500
Sat, 15 Aug 2020 05:40:53 GMT - info: [f5-service-discovery: Task.js] Task ~Consul_SD~HUpGF9mdnFV7JYj2BM~0PCI5uDrnsFPtyxwS9QGIFPc43D failed: connect ECONNREFUSED 10.1.28.90:8500
Sat, 15 Aug 2020 05:40:53 GMT - fine: [f5-service-discovery: Task.js] Error: connect ECONNREFUSED 10.1.28.90:8500
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1078:14)
```

I tried restarting restnoded and restjavad, and I totally uninstalled the appsvcs and service-discovery plugins. The error messages go away, but then as soon as I reinstall the plugins, they come back. I can't seem to find out where exactly these tasks are getting stuck to know how to clear them out. FWIW  10.1.28.90:8500 is a host:port that I tried at one point for consul, that has since stopped connecting (we closed down port 8500 http and only left 8501 https open). That might have something to do with it.

**Comment by chen23** [comment]
FYI I have seen similar issues.  A "hammer" reset method is to delete the "tasks" data-group.  Note that this will wipe out all existing service discovery tasks and will be the equivalent of a "factory" reset.  #308 .  I'm hopeful that when that issue gets resolved it should also address some of the errors that you are seeing as well.

**Comment by chrisjohnson** [comment]
Thanks for the tip on the manual deletion!

**Comment by chen23** [comment]
@chrisjohnson AS3 3.24 has several improvements to Service Discovery.  I'm curious whether you will have a better experience with the updates.  Thanks.
