### ISSUE TITLE
Installation of appsvcs fails

### ISSUE THREAD

**Issue by edarzins** [F5Networks/f5-appsvcs-extension#395]
### Environment
 * Application Services Version: 3.24.0
 * BIG-IP Version: BIG-IP v13.1.3.4 (Build 0.0.5), BIG-VE Azure Marketplace image

### Summary
Installation of appsvcs fails, isn't usable.

### Steps To Reproduce
1. Followed the steps to install appsvcs using the BIG-IP Configuration Utility (https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/installation.html#success)

2. Attempted to verify the installation by sending a GET to the **/mgmt/shared/appsvcs/info** endpoint, but received the following:

```
{
  "code": 404,
  "message": "Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.",
  "referer": "98.38.98.167",
  "restOperationId": 6073118,
  "errorStack": [
    "com.f5.rest.common.RestWorkerUriNotFoundException: Public URI path not registered. Please see /var/log/restjavad.0.log and /var/log/restnoded/restnoded.log for details.",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.cloneAndForwardRequest(ForwarderPassThroughWorker.java:572)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.access$000(ForwarderPassThroughWorker.java:44)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:314)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker$1.completed(ForwarderPassThroughWorker.java:311)",
    "at com.f5.rest.workers.EvaluatePermissions.completeEvaluatePermission(EvaluatePermissions.java:150)",
    "at com.f5.rest.workers.EvaluatePermissions.evaluatePermission(EvaluatePermissions.java:78)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.onForward(ForwarderPassThroughWorker.java:342)",
    "at com.f5.rest.workers.ForwarderPassThroughWorker.onGet(ForwarderPassThroughWorker.java:753)",
    "at com.f5.rest.common.RestWorker.callDerivedRestMethod(RestWorker.java:1230)",
    "at com.f5.rest.common.RestWorker.callRestMethodHandler(RestWorker.java:1148)",
    "at com.f5.rest.common.RestServer.processQueuedRequests(RestServer.java:1401)",
    "at com.f5.rest.common.RestServer.access$000(RestServer.java:48)",
    "at com.f5.rest.common.RestServer$1.run(RestServer.java:329)",
    "at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)",
    "at java.util.concurrent.FutureTask.run(FutureTask.java:262)",
    "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)",
    "at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)",
    "at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)",
    "at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)",
    "at java.lang.Thread.run(Thread.java:748)\n"
  ],
  "kind": ":resterrorresponse"
}
```

### Expected Behavior
Expected appsvcs to start, but it didn't.

### Actual Behavior
appsvcs isn't available after the installation, noticed the following logs in "/var/log/restnoded/restnoded.log"

```
Thu, 10 Dec 2020 15:25:36 GMT - severe: [f5-service-discovery: restWorkerTask.js] {"killed":false,"code":1,"signal":null,"cmd":"tmsh -a list ltm data-group internal /Common/ServiceDiscovery/tasks"}
Thu, 10 Dec 2020 15:25:36 GMT - severe: [RestWorker] [RestWorker] worker failed to start: Error: Command failed: tmsh -a list ltm data-group internal /Common/ServiceDiscovery/tasks
:shared/service-discovery/task

Thu, 10 Dec 2020 15:25:37 GMT - severe: [appsvcs] {"message":"Failed to complete startup. Error: Command failed: tmsh -a create sys folder /Common/appsvcs\n\n    at ChildProcess.exithandler (child_process.js:202:12)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at maybeClose (internal/child_process.js:854:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)","level":"error"}
Thu, 10 Dec 2020 15:25:37 GMT - severe: [RestWorker] [RestWorker] worker failed to load state: [object Object]:shared/appsvcs
```

**Comment by mdditt2000** [comment]
@edarzins what user are you using to install the RPM. Please can you try admin user

**Comment by dstokesf5** [comment]
Closing for inactivity. If you are still encountering issue, please reopen this ticket for a file a new one.
