### ISSUE TITLE
Service Discovery failure from BIG-IP Anywhere example

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-appsvcs-extension#425]
### Environment
BIG-IP External to AWS discovering AWS EC2 instances

### Summary
Using the example declaration below does not discover EC2 instances with tags. The declaration was crafted from the example of BIG-IP Anywhere.

https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/discovery.html?highlight=service%20discovery#using-remote-service-discovery-to-automatically-populate-a-pool-with-big-ip-ve-anywhere

### Steps To Reproduce

reproduced on 3.25 and 3.26 with SD 1.5

1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
        "class": "ADC",
        "schemaVersion": "3.24.0",
        "id": "example-declaration-01",
        "label": "Hackazon",
        "remark": "Simple HTTP application with round robin pool",
        "Hackazon-tagged": {
            "class": "Tenant",
            "defaultRouteDomain": 0,
            "Hackazon": {
                "class": "Application",
                "template": "http",
                "serviceMain": {
                    "class": "Service_HTTP",
                    "virtualAddresses": [
                        "10.0.2.13"
                    ],
                    "pool": "hackazon_pool_tagged"
                },
                "hackazon_pool_tagged": {
                    "class": "Pool",
                    "monitors": [
                        "http"
                    ],
                    "members": [
                        {
                            "servicePort": 81,
                            "addressDiscovery": "aws",
                            "updateInterval": 10,
                            "tagKey": "porsche",
                            "tagValue": "panamera",
                            "addressRealm": "public",
                            "region": "us-west-1",
                            "accessKeyId": "nope",
                            "secretAccessKey": "nopenopenope",
                            "credentialUpdate": false
                        }
                    ]
                }
            }
        }
    }
}
```

2. Observe the following error response:
```json
Thu, 04 Mar 2021 08:18:34 GMT - fine: [f5-service-discovery: getNodes.js] No iid doc found
Thu, 04 Mar 2021 08:18:34 GMT - severe: [f5-service-discovery: getNodes.js] error code: AuthFailure message: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'your'
Thu, 04 Mar 2021 08:18:34 GMT - info: [f5-service-discovery: Task.js] Task ~Common~pHHMgStck786fvaJvlzsS0~YVM7rKo8dDRqpBwKTerE3D failed: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'your'
Thu, 04 Mar 2021 08:18:34 GMT - fine: [f5-service-discovery: Task.js] AuthFailure: Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got 'your'
```
```
Thu, 04 Mar 2021 16:19:38 GMT - fine: [f5-service-discovery: getNodes.js] No iid doc found

Thu, 04 Mar 2021 16:19:38 GMT - severe: [f5-service-discovery: getNodes.js] error code: AuthFailure message: AWS was not able to validate the provided access credentials

Thu, 04 Mar 2021 16:19:38 GMT - info: [f5-service-discovery: Task.js] Task ~Hackazon-tagged~C77RWDIQ4wbQvP~fKHDzC2xhv9ZeO~UxotAZ8GUke7o3D failed: AWS was not able to validate the provided access credentials

Thu, 04 Mar 2021 16:19:38 GMT - fine: [f5-service-discovery: Task.js] AuthFailure: AWS was not able to validate the provided access credentials

    at Request.extractError (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/services/ec2.js:50:35)

    at Request.callListeners (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:106:20)

    at Request.emit (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

    at Request.emit (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:688:14)

    at Request.transition (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:22:10)

    at AcceptorStateMachine.runTo (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/state_machine.js:14:12)

    at /var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/state_machine.js:26:10

    at Request.<anonymous> (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:38:9)

    at Request.<anonymous> (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:690:12)

    at Request.callListeners (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

    at Request.emit (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:78:10)

    at Request.emit (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:688:14)

    at Request.transition (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:22:10)

    at AcceptorStateMachine.runTo (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/state_machine.js:14:12)

    at /var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/state_machine.js:26:10

    at Request.<anonymous> (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:38:9)

    at Request.<anonymous> (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/request.js:690:12)

    at Request.callListeners (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

    at callNextListener (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/sequential_executor.js:96:12)

    at IncomingMessage.onEnd (/var/config/rest/iapps/f5-service-discovery/node_modules/aws-sdk/lib/event_listeners.js:307:13)

    at emitNone (events.js:111:20)

    at IncomingMessage.emit (events.js:208:7)
```

### Expected Behavior
Service Discovery should work

### Actual Behavior
Everything is created except the pool members

**Comment by dstokesf5** [comment]
Confirmed, something is wrong here. Added to our internal product backlog as AUTOTOOL-2308.

**Comment by sunitharonan** [comment]
If you are still looking for a fix, please reach out to us at automation_toolchain_pm@f5.com
