### ISSUE TITLE
Transient authorization errors when using AS3 with sustained traffic 

### ISSUE THREAD

**Issue by mjmenger** [F5Networks/f5-appsvcs-extension#438]
### Environment
 * Application Services Version: 3.26.0
 * BIG-IP Version: 15.1.2.1

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.

When performing load testing on the AS3 endpoint with approximately ten requests per minute, ```401 F5 Authorization Required``` errors show up randomly. Under greater load, they show up more frequently. 
```
HTTP/1.1 401 F5 Authorization Required
{"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare Referrer:x.x.x.x Sender:x.x.x.x","referer":"x.x.x.x","restOperationId":6538112,"kind":":resterrorresponse"}
```

All of the requests are performed using Basic Authentication with the same c

### Steps To Reproduce
1. Setup a Locust instance or similar load testing tool.  [Here is an example](https://github.com/mjmenger/as3-bluegreen/blob/0.1.2/fast/test/AS3-BLUEGREEN.md).
2. Run 10 concurrent users sending AS3 declarations every few seconds. The declaration can be any [legitimate AS3](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/declarations/).
3. Watch the load testing logs for 401 error responses 

### Expected Behavior
If I'm using the same credentials and sending similar declarations repeatedly, there shouldn't be occasional authorization missing errors.

### Actual Behavior
401 F5 Authorization Required errors occur occasionally 

The following is an example of a Jenkins job with retry on failure enabled.
```
Started by user admin
Running as admin
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/as3buffer
[Pipeline] {
[Pipeline] retry
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Echo Request)
[Pipeline] echo
AS3 Declaration: "{\n    \"$schema\": \"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.25.0/as3-schema-3.25.0-3.json\",\n    \"class\": \"AS3\",\n    \"action\": \"deploy\",\n  ...       }\n            }\n        }\n    }\n}"
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post the Declaration)
[Pipeline] script
[Pipeline] {
[Pipeline] httpRequest
HttpMethod: POST
URL: https://x.x.x.x/mgmt/shared/appsvcs/declare
Using authentication: bigip-creds
Sending request to url: https://x.x.x.x/mgmt/shared/appsvcs/declare
Response Code: HTTP/1.1 401 F5 Authorization Required
Response: 
{"code":401,"message":"Authorization failed: no user authentication header or token detected. Uri:http://localhost:8100/mgmt/shared/appsvcs/declare Referrer:x.x.x.x Sender:x.x.x.x","referer":"x.x.x.x","restOperationId":6538112,"kind":":resterrorresponse"}
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
ERROR: Execution failed
hudson.AbortException: Fail: the returned code 401 is not in the accepted range: [[200‥302]]
    at jenkins.plugins.http_request.HttpRequestExecution.responseCodeIsValid(HttpRequestExecution.java:369)
    at jenkins.plugins.http_request.HttpRequestExecution.processResponse(HttpRequestExecution.java:379)
    at jenkins.plugins.http_request.HttpRequestExecution.authAndRequest(HttpRequestExecution.java:295)
    at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:226)
Caused: java.lang.IllegalStateException
    at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:229)
    at jenkins.plugins.http_request.HttpRequestExecution.call(HttpRequestExecution.java:79)
    at hudson.remoting.LocalChannel.call(LocalChannel.java:46)
    at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:353)
    at jenkins.plugins.http_request.HttpRequestStep$Execution.run(HttpRequestStep.java:331)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
    at hudson.security.ACL.impersonate2(ACL.java:449)
    at hudson.security.ACL.impersonate(ACL.java:461)
    at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Retrying
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Echo Request)
[Pipeline] echo
AS3 Declaration: "{\n    \"$schema\": \"https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/3.25.0/as3-schema-3.25.0-3.json\",\n    \"class\": \"AS3\",\n    \"action\": \"deploy\",\n  ...          }\n        }\n    }\n}"
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Post the Declaration)
[Pipeline] script
[Pipeline] {
[Pipeline] httpRequest
HttpMethod: POST
URL: https://x.x.x.x/mgmt/shared/appsvcs/declare
Using authentication: bigip-creds
Sending request to url: https://x.x.x.x/mgmt/shared/appsvcs/declare
Response Code: HTTP/1.1 200 OK
Response: 
{"results":[{"code":200,"message":"success","lineCount":18,"host":"localhost","tenant":"test146","runTime":1532}],"declaration":{"test146":{"class":"Tenant","App":{"class":"Application","service":{"class...{"archiveTimestamp":"2021-03-24T19:48:01.731Z"}}}
Success code from [200‥302]
[Pipeline] echo
Status: 200
[Pipeline] echo
Content: {"results":[{"code":200,"message":"success","lineCount":18,"host":"localhost","tenant":"test146","runTime":1532}],"declaration":{"test146":{"class":"Tenant","App":{"class":"Application","service":{"class":"Service_L4","virtualAddresses":... ective","controls":{"archiveTimestamp":"2021-03-24T19:48:01.731Z"}}}
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // retry
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS


```

**Comment by dstokesf5** [comment]
This is an error message coming from iControl REST (restjavad) before the request is even passed along to AS3. There is nothing that AS3 can do about this. I have found iControl REST is less likely to have these authorization issues when using X-F5-Auth-Token header.
