### ISSUE TITLE
Address_Discovery static node type does not work

### ISSUE THREAD

**Issue by thepowercoders** [F5Networks/f5-appsvcs-extension#660]
### Environment
 * Application Services Version: 3.40.0
 * BIG-IP Version: BIG-IP v16.1.2.2 (Build 0.0.28)

### Summary
When the Class [Address_Discovery](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/refguide/schema-reference.html#address-discovery) is used with addressDiscovery property "static", the declaration either fails, or is accepted and a '200 OK' is returned, but no nodes are added into the configuration.

#### Issue 1: Declaration fails

1. Submit the following declaration:
```json
{
	"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
	"class": "AS3",
	"action": "deploy",
	"persist": true,
	"declaration": {
		"class": "ADC",
		"schemaVersion": "3.40.0",
		"id": "Pool",
		"TEST": {
			"class": "Tenant",
			"Shared": {
				"class": "Application",
				"template": "shared",
				"Test-AD1": {
					"class": "Address_Discovery",
					"addressDiscovery": "static",
					"servers": [
						{
							"name": "myNode3.example.com",
							"address": "192.0.3.10"
						}
					]
				}
			}
		}
	}
}
```

2. Observe the following error response:
```json
	"results": [
		{
			"message": "Cannot read property 'map' of undefined",
			"host": "localhost",
			"tenant": "TEST",
			"code": 422
		}
	],
```

#### Issue 2: Declaration passes but no config is added

1. Submit the following declaration:
```json
{
	"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
	"class": "AS3",
	"action": "deploy",
	"persist": true,
	"declaration": {
		"class": "ADC",
		"schemaVersion": "3.40.0",
		"id": "Pool",
		"TEST": {
			"class": "Tenant",
			"TESTAPP": {
				"class": "Application",
				"Test-AD2": {
					"class": "Address_Discovery",
					"addressDiscovery": "static",
					"serverAddresses": [
						"192.168.1.1"
					],
					"shareNodes": true
				},
				"My_pool": {
					"class": "Pool",
					"members": [
						{
							"servicePort": 8080,
							"addressDiscovery": {
								"use": "Test-AD2"
							}
						}
					]
				}
			}
		}
	}
}
````

2. Observe the following OK response:

```` json
	"results": [
		{
			"code": 200,
			"message": "success",
			"lineCount": 17,
			"host": "localhost",
			"tenant": "TEST",
			"runTime": 1347
		}
````

However, when checking configuration - no node is added, and the My_pool pool has no members.

![image](https://user-images.githubusercontent.com/32461620/196203067-a70f2e7f-3900-4554-b3de-1ce9b43daa4b.png)

### Expected Behavior
According to the API Specification, in Address_Discovery there should be the ability to add a static node with either the serverAddresses or servers property and this should populate the 'Nodes' on the LTM - either in the partition given, or in /Common if the "shareNodes" option is included.

### Actual Behavior
Either the declaration fails, or the declaration appears to succeed but no configuration is created.

The LTM starts streaming out the following log in the restnoded.log:

```
Mon, 17 Oct 2022 14:29:49 GMT - info: [f5-service-discovery: Task.js] Task ~TEST~7eAU4SMxiiKuv90R2vDmkeShPea~H2yhIjjD6RAT4ak3D failed: The following nodes are not on the BIG-IP: [{"id":"192.168.1.1"}]
Mon, 17 Oct 2022 14:29:49 GMT - fine: [f5-service-discovery: Task.js] Error: The following nodes are not on the BIG-IP: [{"id":"192.168.1.1"}]
    at executeCommand.then (/var/config/rest/iapps/f5-service-discovery/lib/TmshUtil.js:426:35)
    at tryCatcher (/usr/share/rest/node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/share/rest/node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/share/rest/node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

However, if the addressDiscovery static is used within the 'Pool' configuration, everything works fine for both serverAddresses and servers property options - example below:

```` json
{
	"$schema": "https://raw.githubusercontent.com/F5Networks/f5-appsvcs-extension/master/schema/latest/as3-schema.json",
	"class": "AS3",
	"action": "deploy",
	"persist": true,
	"declaration": {
		"class": "ADC",
		"schemaVersion": "3.40.0",
		"id": "Pool",
		"TEST": {
			"class": "Tenant",
			"Shared": {
				"class": "Application",
				"template": "shared",
				"My_pool": {
					"class": "Pool",
					"members": [
						{
							"servicePort": 8080,
							"addressDiscovery": "static",
							"serverAddresses": [
								"192.0.2.2"
							],
							"servers": [
								{
									"name": "myNode1.example.com",
									"address": "192.0.2.10"
								}
							]
						}
					]
				}
			}
		}
	}
}
````

**Comment by antonywm** [comment]
is there any update on this? It's a pretty critical bug which means the address discovery static option is not available currently

**Comment by mdditt2000** [comment]
@antonywm 3.44.0-1 Build available that resolves this issue.

**Comment by thepowercoders** [comment]
confirmed all working perfectly now for both scenarios shown above - thanks very much for this fix as it removes a manual step now in our deployment ❤️
