### ISSUE TITLE
panic: interface conversion: interface {} is string, not float64

### ISSUE THREAD

**Issue by nanjingayang** [F5Networks/f5-appsvcs-extension#665]
### Environment
 * Application Services Version:3.41.0
 * BIG-IP Version:BIG-IP 15.1.2.1 Build 0.0.10 Point Release 1

### Summary
Please also include information about the reproducibility and the severity/impact of the issue.
when I test your example: Using GSLB features in a declaration, find the error information below.

### Steps To Reproduce
1. Submit the following declaration:
```json
{
    "class": "AS3",
    "action": "deploy",
    "persist": true,
    "declaration": {
    "class": "ADC",
    "schemaVersion": "3.37.0",
    "id": "GSLB_Sample",
    "Common": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "testDataCenter": {
                "class": "GSLB_Data_Center"
            },
            "testProberPool": {
                "class": "GSLB_Prober_Pool",
                "enabled": true,
                "lbMode": "round-robin",
                "members": []
            },
            "testServer": {
                "class": "GSLB_Server",
                "dataCenter": {
                    "use": "testDataCenter"
                },
                "devices": [
                    {
                        "address": "1.2.3.7"
                    }
                ],
                "proberPreferred": "pool",
                "proberPool": {
                    "use": "testProberPool"
                },
                "virtualServers": [
                    {
                        "address": "1.2.3.8",
                        "port": 5050
                    },
                    {
                        "address": "2001:0db8:85a3:0000:0000:8a2e:0370:7334",
                        "port": 5051
                    }
                ]
            }

        }
    }
}
}
```

2. Observe the following error response:
```json
{
bigip_as3.as3-example1: Still creating... [2m1s elapsed]
bigip_as3.as3-example1: Still creating... [2m11s elapsed]
╷
│ Error: Plugin did not respond
│
│   with bigip_as3.as3-example1,
│   on main.tf line 15, in resource "bigip_as3" "as3-example1":
│   15: resource "bigip_as3"  "as3-example1" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵

Stack trace from the terraform-provider-bigip_v1.16.0.exe plugin:

panic: interface conversion: interface {} is string, not float64

goroutine 70 [running]:
github.com/f5devcentral/go-bigip.(*BigIP).PostAs3Bigip(0xdd4d37?, {0xc000500300, 0x2db}, {0xc00054c5d8, 0x6})
        github.com/f5devcentral/go-bigip@v0.0.0-20221108061446-8699e93dd85a/as3bigip.go:77 +0x1848
github.com/F5Networks/terraform-provider-bigip/bigip.resourceBigipAs3Create(0xc8ec00?, {0xda3540?, 0xc0003a2700})
        github.com/F5Networks/terraform-provider-bigip/bigip/resource_bigip_as3.go:191 +0x3cc
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000648400, 0xc000560280, 0xc000552200, {0xda3540, 0xc0003a2700})
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/resource.go:305 +0x438
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc000649880, 0xc0000fb818, 0xc00054c168?, 0x8?)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/helper/schema/provider.go:294 +0x70
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000590208, {0xc0001e2660?, 0x3fac66?}, 0xc0001e2660)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/helper/plugin/grpc_provider.go:885 +0x805
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xd6a120?, 0xc000590208}, {0xf7b370, 0xc00054e150}, 0xc0001e2600, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.1.0/internal/tfplugin5/tfplugin5.pb.go:3189 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020c480, {0xf7f3e0, 0xc0002b2000}, 0xc0004c2f00, 0xc000088e10, 0x1553560, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:995 +0xe1e
google.golang.org/grpc.(*Server).handleStream(0xc00020c480, {0xf7f3e0, 0xc0002b2000}, 0xc0004c2f00, 0x0)
        google.golang.org/grpc@v1.23.0/server.go:1275 +0xa16
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.23.0/server.go:710 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.23.0/server.go:708 +0xea

Error: The terraform-provider-bigip_v1.16.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.}
```

### Expected Behavior
can apply successfully
### Actual Behavior
A clear and concise description of what actually happens.
Please include any applicable error output.

**Comment by pgouband** [comment]
Hi @nanjingayang,
I tried your AS3 declaration with BIG-IP version 15.1.2.1, TF provider 1.16 and Application Services Version:3.41.0 with success.
I tried without AS3 rpm installed, without DNS provisioned but I can't replicate your issue.
Have you tried from another TF client?

**Comment by nanjingayang** [comment]
thanks for your reply,I found the route cause is too many wideip will cause this.(10000).and  I encounter many other error  when use  as3,such as  slowly.  return  success  with no object created.can find error in f5.   as3  is just so so.发自我的手机-------- 原始邮件 --------发件人： Patrick ***@***.***>日期： 2022年12月2日周五 22:47收件人： F5Networks/f5-appsvcs-extension ***@***.***>抄送： nanjingayang ***@***.***>, Mention ***@***.***>主    题： Re: [F5Networks/f5-appsvcs-extension] panic: interface conversion: interface {} is string, not float64 (Issue #665)
Hi @nanjingayang,
I tried your AS3 declaration with BIG-IP version 15.1.2.1, TF provider 1.16 and Application Services Version:3.41.0 with success.
I tried without AS3 rpm installed, without DNS provisioned but I can't replicate your issue.
Have you tried from another TF client?

**Comment by nanjingayang** [comment]
I read this articles. I test with three  devices.but the production environment is full of all kinds conditions.发自我的手机-------- 原始邮件 --------发件人： Patrick ***@***.***>日期： 2022年12月3日周六 00:03收件人： F5Networks/f5-appsvcs-extension ***@***.***>抄送： nanjingayang ***@***.***>, Mention ***@***.***>主    题： Re: [F5Networks/f5-appsvcs-extension] panic: interface conversion: interface {} is string, not float64 (Issue #665)
Hi @nanjingayang,
Have you followed the best practices about AS3?
https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/latest/userguide/best-practices.html?highlight=resource%20provisioning

**Comment by pgouband** [comment]
Hi @nanjingayang,

I'm not sure to understand your issue.
Could you elaborate and provide some logs?
